-- CreateTable
CREATE TABLE "Widget" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),

    CONSTRAINT "Widget_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PageViews" (
    "name" STRING NOT NULL,
    "views" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY
);

-- CreateIndex
CREATE UNIQUE INDEX "PageViews_name_key" ON "PageViews"("name");
